### PR TITLE
Update PA to 8/13

### PR DESCRIPTION
**Pull request by colincadams**
## Description of the change

Anna is going to drop the 8/13 data into prod now, so it will start running through ingest. Want to have this change ready for once it makes it all the way through.

Weekly data is still a no go 😢 

## Type of change

- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

N/A

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by macfarlandian — APPROVED** [review]
arrived like clockwork

**Comment by ageiduschek** [comment]
FWIW I think the weekly data is actually as good as it's going to get, but it might be a full ingest rerun worth of time before we are able to use it.

**Review by ageiduschek — CHANGES_REQUESTED** [review]
PA crashed over the weekend so don't land this yet

**Review by ageiduschek — APPROVED** [review]
You can land this now!

**Pull request merged**
