### PR TITLE
Improve performance of flaky FE tests

### LINKED ISSUE #353: Tests involving animated elements fail intermittently
**What needs to be done? Why does it need to be done?**
Test behavior in `spotlight-client` should be more consistent - a handful of tests rely on Testing Library's `waitForElementToBeRemoved` function or `waitFor`/`findBy` queries to accommodate unpredictable rendering delays related to animated transitions. These delays are so unpredictable that the tests do not consistently pass or fail; this can be observed both locally and in CI, but intermittently and thus far unpredictably.

**Additional context**
This is a nuisance but thus far re-running the tests until they pass has been an effective workaround. If that stops being the case, this will become a more urgent issue.

It's not clear whether this is a simple timing issue or something more fundamental caused by the various holes in JSDOM (unsupported APIs tend to exhibit surprising behavior rather than just failing, which has bedeviled these tests on multiple occasions before)

### PR DESCRIPTION
**Pull request by macfarlandian**
## Description of the change

Tweaks a few of the frontend integration tests to stop intermittent failures. No guarantees really but whereas before the failure rate was creeping up above 75% at times, with these changes I have yet to trigger a failure in a dozen-plus runs across my local and CI. 

I think the main culprit was the *ByRole queries in Testing Library, which apparently are [known to be resource hogs](https://github.com/testing-library/dom-testing-library/issues/820) to the point where they can overwhelm the async polling utilities and cause timeouts and/or failures. Improvements can be had by decoupling the role check from the visibility check, or by just using a different query type.

I only had to change a few of the tests that were known to fail in order to see an improvement; my suspicion is that the poor performance had some kind of cascade effect? Most of the ones I changed were ones that had large DOM trees for the queries to sift through, or that were maybe compounded by animated transitions or something. 

Hopefully this is not too brittle a fix? I am hoping we can avoid a more radical change along the lines of, like, scrapping integration tests in favor of smaller unit tests, etc.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #353

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by macfarlandian** [comment]
lol spoke too soon, got myself an intermittent failure! please stand by

**Comment by macfarlandian** [comment]
ok well after another like two dozen test runs I can say with certainty that this is .... not worse

**Review by daschi — COMMENTED** [review]
I'm having trouble getting the tests to pass locally, I think maybe there's something up with my env? Maybe we can pair on it later today. 

I have a `.env.test` file in `spotlight-client/` with `REACT_APP_API_URL=http://localhost:3002/`, do I also need a `.env.test` file in `spotlight-api`?

**Comment by macfarlandian** [comment]
@daschi no you shouldn't need any config besides that ... possibly removing the trailing slash from that url would help? if not then yes let's pair

**Review by daschi — APPROVED** [review]

**Pull request merged**
