### PR TITLE
UI polish for recidivism chart

### LINKED ISSUE #252: Recidivism UI polish
**What needs to be done? Why does it need to be done?**
Assorted small UI tweaks not worth ticketing individually. 

- [x] P0: Change "select all" to "deselect all" when all are selected
- [x] P0: Start line chart at zero so that 1-year followup period is visible for all years ~(investigate first)~ _(investigation says this is legit!)_
- [x] P1: Preview the lines in the cumulative recidivism chart upon hover
- [x] include color-coding in the tooltip
- [x] highlight cohort selection menu items with a darker shade instead of the highlight color 
- [x] don't reset demographic view when deselecting one year and selecting another one

### PR DESCRIPTION
**Pull request by macfarlandian**
## Description of the change

Several small polish items concerned behavior in the line chart; the changes are all grouped together here. 

- the lines all start at year zero now, to visualize the slope for the first year and make sure cohorts with only one year of data are always visible
- tooltip includes the color swatches to help match values with lines
- highlighted cohort is always rendered even if it is not selected. This only really applies to deselected items highlighted in the dropdown menu, and this behavior is not enabled when a single-year demographic breakdown is applied

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #252

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by daschi — APPROVED** [review]
Looks great! This is unrelated to the changes, but I was curious about the demographic option being reset whenever a year is changed, and wanted to ask if it's the intended behavior for this chart. 

Here's the flow if I wanted to change the year I'm viewing for a particular demographic:
- Select a single year
- Select a demographic 
- Deselect a year and select another year
- Demographic resets to Total, so I reselect the demographic

**Comment by macfarlandian** [comment]
@daschi it is intended but I guess in the use case you are describing it's not strictly necessary. The view resets whenever the number of cohorts is not equal to one, which means setting to zero resets it. Seems kind of silly when you spell it out like that! (It's probably an easy fix, I will look into it and add to this PR if it's sufficiently small)

**Comment by macfarlandian** [comment]
good call @daschi I got that change approved and have added it here

**Review by daschi — APPROVED** [review]
nice! 🥇

**Pull request merged**
